-- Create the comments table
create table public.comments (
    id bigint generated by default as identity primary key,
    project_id text not null,
    user_name text not null,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.comments enable row level security;

-- Create a policy that allows anyone to read comments
create policy "Anyone can read comments"
on public.comments for select
to anon
using (true);

-- Create a policy that allows authenticated users to insert comments
create policy "Anyone can insert comments"
on public.comments for insert
to anon
with check (true);
